### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by dadashzadeh** [bisohns/search-engine-parser#159]
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Program Files\Python39\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
<search_engine_parser.core.base.SearchResult at 0x1f402d77ac0>

**Comment by Alexell** [comment]
I get the same error from time to time.

**Comment by moewiee** [comment]
upgrade `fake-useragent` version to 0.1.13 worked for me.

`pip3 install fake-useragent==0.1.13`
